name = "url-redirect"
main = "src/index.js"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./public"

[vars]
# 在环境变量中设置JWT密钥（应当使用随机生成的值）
JWT_SECRET = "sgdsagdfagadfgdfagdd"
# 用于管理员登录的密码
ADMIN_PASSWORD = "change_this_to_secure_password"

[[d1_databases]]
binding = "DB"
database_name = "xhs"
database_id = "2e8061aa-7da5-4d6d-b2ac-a7ffe2ee81e2"  # 需要替换为实际的数据库ID 