name = "url-redirect"
main = "redirect.js"
compatibility_date = "2023-09-01"
# 添加以下两行，启用ES模块支持和Node.js兼容性
type = "javascript"
compatibility_flags = ["nodejs_compat"]

# D1数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "xhs"
database_id = "c1f993fd-defc-4a55-8189-47066ca9a773"

# 环境变量配置
[vars]
# 管理员密码 - 请更改为安全的密码
# 重要: 如果您未更改此默认密码，您将无法登录系统!
# 必须将此密码更改为您自己设置的密码才能正常登录
ADMIN_PASSWORD = "your_secure_password_here"

[build]
command = ""

[env.production]
# 生产环境特定设置
route = ""
# 如果需要自定义域名，取消下面一行注释并填写域名
# routes = [
#   { pattern = "example.com/*", zone_name = "example.com" }
# ]

# 生产环境变量配置 - 覆盖默认变量
[env.production.vars]
# 在实际部署时设置密码
# ADMIN_PASSWORD = "your_production_secure_password" 