name = "url-redirect"
main = "src/index.js"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

[vars]
# 在环境变量中设置JWT密钥（应当使用随机生成的值）
JWT_SECRET = "sgdsagdfagadfgdfagdd"
# 用于管理员登录的密码
ADMIN_PASSWORD = "change_this_to_secure_password"

[[d1_databases]]
binding = "DB"
database_name = "xhs"
database_id = "2e8061aa-7da5-4d6d-b2ac-a7ffe2ee81e2" # Replace with your actual DB ID

# Cron Triggers for scheduled tasks
[triggers]
# "<cron string>" = [ "<schedule name>" ] (optional name)
# Example: Run daily at 1:00 AM UTC
crons = [ "0 1 * * *" ]

[[r2_buckets]]
binding = "MY_R2_BUCKET" # 这个名称将用于在 Worker 代码中访问 R2
bucket_name = "xhs"